---
- block:
  - name: install acme.sh packages
    ansible.builtin.unarchive:
      src: "https://github.com/acmesh-official/acme.sh/archive/refs/tags/{{ acmesh_version }}.zip"
      dest: "/tmp/acme.sh-{{ acmesh_version }}.zip"
    ansible.builtin.command:
      cmd: "./acme.sh --install -m {{ acmesh_email }}"
      args:
        chdir: "/tmp/acme.sh-{{ acmesh_version }}"
  tags:
    - acmesh
