---
- block:
  - name: install socat package
    ansible.builtin.apt:
      name: "socat"
      state: "present"
  - name: fetch acme.sh package
    ansible.builtin.unarchive:
      remote_src: yes
      src: "https://github.com/acmesh-official/acme.sh/archive/refs/tags/{{ acmesh_version }}.zip"
      dest: "/tmp"
  - name: install acme.sh package
    ansible.builtin.command:
      cmd: "./acme.sh --install -m {{ acmesh_email }}"
      args:
        chdir: "/tmp/acme.sh-{{ acmesh_version }}"
  tags:
    - acmesh
